project:
  render: 
        - "*.qmd"
        - "!devel-workshops/"
  type: website
  output-dir: docs

website:
  title: "Quantitative Methods - Workshop and Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: feedback-assignments.qmd
        text: Feedback

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



