project:
  type: website

website:
  title: "Quantitative Methods - Workshop, Assigments and Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignments.qmd
        text: Assignments
      - href: workshops.qmd
        text: Workshops

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



