---
title: "Assignments"
format: html
---

|Assignment |Due date |Included in portfolio |Group assignment|
| :--- | :---: | ---:| ---:|
|[Descriptive statistics, reliability and validity, tools for reproducible data science](assignment-1.html)| 2022-09-26 |Yes|Yes|
|[Regression models and prediction from data](assignment-2.html)|2022-11-04|No|Yes|
|Extraction and analysis of DNA |2022-11-23|Optional^a^|Yes|
|Extraction of RNA and analysis of qPCR experiments|2022-11-23|Optional^a^|Yes|
|Extraction and analysis of Protein|2022-11-23|Optional^a^|Yes|
|Philosophy of science^b^ (See canvas)|2022-10-28|Yes|No|
|[Drawing inference from statistical models and statistical power](assignment-3.html)|2022-11-11|No|Yes|
|[Study designs](assignment-4.html)|2022-11-25|Yes|No|
|[Analyzing repeated measures experiments](assignment-5.html)|2022-11-25|Yes|No|


 <font size="2">^a^ Select one laboratory assignments for your portfolio exam. All groups presents one selected method on 2022-11-23. ^b^ This assignment is presented in connection with lectures. 
 </font>